"""Dotool key mapping tables used by Talon key translation."""

# Dotool key name mappings; extend as needed.
MODIFIER_ALIASES = {
    "ctrl": "ctrl",
    "control": "ctrl",
    "alt": "alt",
    "option": "alt",
    "shift": "shift",
    "super": "super",
    "win": "super",
    "cmd": "super",
    "command": "super",
    "altgr": "altgr",
    "ralt": "altgr",
    "rctrl": "ctrl",
    "rshift": "shift",
    "rsuper": "super",
    "rwin": "super",
}

KEY_NAME_MAP = {
    "escape": "esc",
    "esc": "esc",
    "enter": "enter",
    "return": "enter",
    "tab": "tab",
    "space": "space",
    "backspace": "backspace",
    "delete": "delete",
    "insert": "insert",
    "home": "home",
    "end": "end",
    "pageup": "pageup",
    "pagedown": "pagedown",
    "up": "up",
    "down": "down",
    "left": "left",
    "right": "right",
    "printscr": "print",
    "printscreen": "print",
    "menu": "menu",
}

SYMBOL_KEY_MAP = {
    ",": "x:comma",
    ".": "x:period",
    "/": "x:slash",
    ";": "x:semicolon",
    "'": "x:apostrophe",
    "[": "x:bracketleft",
    "]": "x:bracketright",
    "\\": "x:backslash",
    "`": "x:grave",
    "-": "x:minus",
    "=": "x:equal",
    "!": "x:exclam",
    "@": "x:at",
    "#": "x:numbersign",
    "$": "x:dollar",
    "%": "x:percent",
    "^": "x:asciicircum",
    "&": "x:ampersand",
    "*": "x:asterisk",
    "(": "x:parenleft",
    ")": "x:parenright",
    "_": "x:underscore",
    "+": "x:plus",
    "{": "x:braceleft",
    "}": "x:braceright",
    "|": "x:bar",
    ":": "x:colon",
    '"': "x:quotedbl",
    "<": "x:less",
    ">": "x:greater",
    "?": "x:question",
    "~": "x:asciitilde",
}
